#!/usr/bin/env python3
"""
Generate detailed coastline data for ESP32 azimuthal map display.
Downloads Natural Earth 110m coastlines and converts to C header format.

Usage: python generate_coastlines.py > ../include/coastline_data.h

Requirements: pip install requests
"""
import json
import urllib.request
import sys
import os

# Natural Earth 110m coastlines GeoJSON (from GitHub)
NE_110M_URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_coastline.geojson"
NE_50M_URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_coastline.geojson"

def download_geojson(url):
    """Download GeoJSON data from URL."""
    print(f"Downloading from {url}...", file=sys.stderr)
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=30) as response:
        return json.loads(response.read().decode('utf-8'))

def simplify_segment(coords, tolerance=0.3):
    """Douglas-Peucker line simplification to reduce point count."""
    if len(coords) <= 2:
        return coords
    
    # Find the point with the maximum distance from the line between start and end
    start = coords[0]
    end = coords[-1]
    
    max_dist = 0
    max_idx = 0
    
    for i in range(1, len(coords) - 1):
        # Distance from point to line
        dx = end[0] - start[0]
        dy = end[1] - start[1]
        line_len_sq = dx * dx + dy * dy
        
        if line_len_sq == 0:
            dist = ((coords[i][0] - start[0])**2 + (coords[i][1] - start[1])**2)**0.5
        else:
            t = max(0, min(1, ((coords[i][0] - start[0]) * dx + (coords[i][1] - start[1]) * dy) / line_len_sq))
            proj_x = start[0] + t * dx
            proj_y = start[1] + t * dy
            dist = ((coords[i][0] - proj_x)**2 + (coords[i][1] - proj_y)**2)**0.5
        
        if dist > max_dist:
            max_dist = dist
            max_idx = i
    
    if max_dist > tolerance:
        left = simplify_segment(coords[:max_idx + 1], tolerance)
        right = simplify_segment(coords[max_idx:], tolerance)
        return left[:-1] + right
    else:
        return [start, end]

def geojson_to_segments(geojson, simplification=0.2):
    """Extract coastline segments from GeoJSON, return as list of [(lat,lon), ...]."""
    segments = []
    
    for feature in geojson['features']:
        geom = feature['geometry']
        
        if geom['type'] == 'LineString':
            coords = geom['coordinates']  # [lon, lat] pairs
            if len(coords) >= 2:
                # Simplify
                simplified = simplify_segment(coords, simplification)
                segment = [(lat, lon) for lon, lat in simplified]
                if len(segment) >= 2:
                    segments.append(segment)
                    
        elif geom['type'] == 'MultiLineString':
            for line in geom['coordinates']:
                if len(line) >= 2:
                    simplified = simplify_segment(line, simplification)
                    segment = [(lat, lon) for lon, lat in simplified]
                    if len(segment) >= 2:
                        segments.append(segment)
    
    return segments

def format_header(segments):
    """Format segments as C header file."""
    total_points = sum(len(s) for s in segments) + len(segments)  # +separators
    total_floats = total_points * 2
    est_kb = total_floats * 4 / 1024
    
    lines = []
    lines.append("#pragma once")
    lines.append("// World coastline data from Natural Earth for azimuthal map display")
    lines.append(f"// {len(segments)} segments, ~{sum(len(s) for s in segments)} points, ~{est_kb:.0f}KB flash")
    lines.append("// Generated by generate_coastlines.py - do not edit manually")
    lines.append("// {999, 999} separates segments.")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("static const float COASTLINE_DATA[] PROGMEM = {")
    
    for seg_idx, segment in enumerate(segments):
        # Format 4 points per line
        point_strs = []
        for lat, lon in segment:
            point_strs.append(f"{lat:.1f}f, {lon:.1f}f")
        
        # Write in groups of 4
        for i in range(0, len(point_strs), 4):
            chunk = point_strs[i:i+4]
            prefix = "    "
            lines.append(prefix + ",  ".join(chunk) + ",")
        
        lines.append("    999.0f, 999.0f,")
        if seg_idx < len(segments) - 1:
            lines.append("")
    
    lines.append("};")
    
    return "\n".join(lines)

def main():
    # Try 50m first for more detail, fall back to 110m
    for url, label in [(NE_50M_URL, "50m"), (NE_110M_URL, "110m")]:
        try:
            geojson = download_geojson(url)
            print(f"Using Natural Earth {label} data", file=sys.stderr)
            break
        except Exception as e:
            print(f"Failed to download {label}: {e}", file=sys.stderr)
            continue
    else:
        print("ERROR: Could not download coastline data", file=sys.stderr)
        sys.exit(1)
    
    # Use tighter simplification for 50m data to keep detail without being huge
    tolerance = 0.15 if label == "50m" else 0.1
    segments = geojson_to_segments(geojson, simplification=tolerance)
    
    # Filter out degenerate segments (< 3 points or very small spans)
    good_segments = []
    for seg in segments:
        if len(seg) < 2:
            continue
        # Skip segments where all points are essentially the same
        lats = [p[0] for p in seg]
        lons = [p[1] for p in seg]
        span = max(max(lats) - min(lats), max(lons) - min(lons))
        if span < 0.05:  # Skip tiny specks < ~5km
            continue
        good_segments.append(seg)
    segments = good_segments
    
    total_points = sum(len(s) for s in segments)
    print(f"Extracted {len(segments)} segments with {total_points} total points", file=sys.stderr)
    
    # Output the header
    output = format_header(segments)
    
    # Write to file
    out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 
                            "include", "coastline_data.h")
    with open(out_path, 'w') as f:
        f.write(output + "\n")
    
    est_kb = total_points * 2 * 4 / 1024
    print(f"Written to {out_path} (~{est_kb:.0f}KB flash)", file=sys.stderr)

if __name__ == "__main__":
    main()
